### PR TITLE
A little bit of changes

### PR DESCRIPTION
**Pull request by mentaljam**
Hello!

I just wanted to fix some UI issues and then could not stop. I tried to comment informatively my commits, and I hope you would find my pr useful)

### CODE REVIEW

**Comment by Lechindianer** [comment]
Hey Petr,
sorry for the late reply, I don't know how I could have overlooked this :( Thank you for the PR! 👍 
I don't have a SailfishOS-based phone myself anymore (my Jolla is dead) , so if you can imagine to improve this app further maybe you wanna take over ownership on openrepos?

**Comment by mentaljam** [comment]
Hi!

> my Jolla is dead

Oh, it's such a pity!

> maybe you wanna take over ownership on openrepos

Yes, with a pleasure. How can it be done?

**Comment by Lechindianer** [comment]
I didn't find an option to change ownership :/ I might just write that it's an outdated version and linking to your version? Do you already have an account over there?

**Comment by mentaljam** [comment]
Yes, I'll publish a new version in a short time and let you know.

**Comment by mentaljam** [comment]
Done! https://openrepos.net/content/osetr/beerware-fork

**Comment by Lechindianer** [comment]
I link to your fork and OpenRepo now. Thanks for taking ownership!

**Pull request closed without merging**
